//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P07_01_DI_Contactos_TAPIADOR_rodrigo.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P07_01_DI_Contactos_TAPIADOR_rodrigo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AvgPrcByCt.
        /// </summary>
        public static string AvgPrcByCt {
            get {
                return ResourceManager.GetString("AvgPrcByCt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DataGraphics.
        /// </summary>
        public static string DataGraphics {
            get {
                return ResourceManager.GetString("DataGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ImageLink.
        /// </summary>
        public static string ImageLink {
            get {
                return ResourceManager.GetString("ImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InfPrCt.
        /// </summary>
        public static string InfPrCt {
            get {
                return ResourceManager.GetString("InfPrCt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NavCharacters.
        /// </summary>
        public static string NavCharacters {
            get {
                return ResourceManager.GetString("NavCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NavExit.
        /// </summary>
        public static string NavExit {
            get {
                return ResourceManager.GetString("NavExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NavHome.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NavLocations.
        /// </summary>
        public static string NavLocations {
            get {
                return ResourceManager.GetString("NavLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NavSettings.
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PrdsByCt.
        /// </summary>
        public static string PrdsByCt {
            get {
                return ResourceManager.GetString("PrdsByCt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PrdsWthtCts.
        /// </summary>
        public static string PrdsWthtCts {
            get {
                return ResourceManager.GetString("PrdsWthtCts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residents.
        /// </summary>
        public static string Residents {
            get {
                return ResourceManager.GetString("Residents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TtlPrds.
        /// </summary>
        public static string TtlChtrs {
            get {
                return ResourceManager.GetString("TtlChtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TtlCts.
        /// </summary>
        public static string TtlLcts {
            get {
                return ResourceManager.GetString("TtlLcts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
